Added jupyternotebook and dataset for ML experimentation demo
treeverse/lakeFS-samples pull request #50
Opened 2023-04-20 15:19 UTC by vinodhini-sd

Added ML experimentation demo for structured data

2023-04-20 16:34 UTC, rmoff commented
can you also add an entry to the root README in the repo too please

2023-04-20 16:34 UTC, rmoff requested changes

2023-04-20 16:34 UTC, rmoff commented on 10-ml-experimentation-with-lakeFS-structured-data/README.md
is it worth expanding the README to say how to run the notebook, and/or to link to our [docs pages](https://docs.lakefs.io/use_cases/reproducibility.html)  ?

2023-04-20 21:26 UTC, vinodhini-sd commented on 10-ml-experimentation-with-lakeFS-structured-data/README.md
Yep, updated the readme with detailed instructions.

2023-04-20 21:30 UTC, vinodhini-sd commented
@rmoff - TODO: Add link to the blog once it is up on the website.

2023-04-21 07:30 UTC, rmoff approved these changes

2023-04-21 16:11 UTC, merged